### ISSUE TITLE
Set Elementus Info Type don`t work (don`t split right way)

### ISSUE THREAD

**Issue by AlexBnew** [lucoiso/UEElementusInventory#13]
Hello, I installed the plugin. In the project, I needed to set the Elementus Item Info, but after the Split Structure Pin, the Item Id does not appear. It doesn't appear anywhere.

![bug](https://user-images.githubusercontent.com/104918515/212488005-e5b8811c-a4d2-40e7-90c9-de9bae53d47b.png)
![image](https://user-images.githubusercontent.com/104918515/212488117-8be459e9-a962-43aa-886a-66de2e6eb119.png)
![image](https://user-images.githubusercontent.com/104918515/212488131-72ed2a42-2d4a-41a7-8a35-592a8884600a.png)

**Comment by AlexBnew** [comment]
I also tested it and it`s works only on widgets. But I need to set item info in actor

**Comment by lucoiso** [comment]
Hello @AlexBnew ! : )

Created a new branch and made a commit changing the ItemID UProperty in Elementus Item Info Struct to have EditAnywhere and BlueprintReadWrite metas: https://github.com/lucoiso/UEElementusInventory/tree/hotfix/EXPOSE-ID-SET-13

This change exposed the ItemID property to setters in actors too:

![image](https://user-images.githubusercontent.com/77353979/212544345-713b5e1d-c6d4-4534-b35a-e3ea22e0b855.png)

**Comment by AlexBnew** [comment]
Thanks you for responding so quickly, it works now
