### ISSUE TITLE
Allow empty slots in inventory

### ISSUE THREAD

**Issue by AlexBnew** [lucoiso/UEElementusInventory#15]
Hello, the problem is described in the picture.
Is it possible to implement the option to resize the Inventory Component Array with empty slots? I don't know if this is a plugin problem or a similar task can be solved already, but I don't understand the functionality of the plugin and how it works to do it

![coment](https://user-images.githubusercontent.com/104918515/215119255-61f54a2d-9ce1-4ee8-a884-53f495b518ca.png)

**Comment by AlexBnew** [comment]
The main reason why it is not possible to make empty slots for recording is that an empty slot has Quantity=1, and if Quantity=0, then Unreal Crush

**Comment by lucoiso** [comment]
Hello @AlexBnew ! Thanks for the info! : )

I've started working in this feature and already sent a commit with a new property in the InventoryComponent: bAllowEmptySlots

This option will allow the component to replace items with quantity <= 0 with an empty item info:
```
const FElementusItemInfo FElementusItemInfo::EmptyItemInfo(FPrimaryElementusItemId(), -1);
```

**Comment by AlexBnew** [comment]
Hello, yes, I have already found a way to make the necessary inventory without changes in the plugin. Therefore, I just want to add that it would be nice to make more detailed documentation - how the functions work, how the components in the plugin work and why they are needed
Thank you for your work
